### ISSUE TITLE
 Permission denied

### ISSUE THREAD

**Issue by ckxkexing** [woc-hack/tutorial#16]
Hello, expert, I filled out the form, but I still can't connect to ssh. Do I need to wait for the review?

**Comment by noah-22** [comment]
Hello @ckxkexing. Yes, an admin must register your ssh credentials with the servers before you can login. 

I am not admin and therefore cannot do this, but am simply advising you of the process. Have a great day!

**Comment by ckxkexing** [comment]
i'm appreciate for your kindness.it works to me now .Have a great day! @noah-22
