### ISSUE TITLE
maps projects to its core developers

### ISSUE THREAD

**Issue by audrism** [woc-hack/tutorial#19]
its in mongodb. P_metadata.Version (current version is T)

Please note that P is a deforked project, so it may correspond to multiple repos
as noted in the tutorial 

On 9/27/21 8:45 PM, Hongbo Fang wrote:
> Hi Audris:
>      I'm trying to use world of code data for research, it seems to me that you mentioned before there is a table which 
> maps projects to its core developers, but I didn't seem to find it in the woc instruction. If this exists, can you 
> direct me to the file?
> 
>      Thanks a lot!
> 
> Best,
> Hongbo
>

**Comment by fhbzc** [comment]
Hi Audris, several follow-up question:

1. 

I'm trying to use pymongo to get all projects and its corresponding core authors, even a simple query like

      client = pymongo.MongoClient("mongodb://da1.eecs.utk.edu/")
      db = client.WoC
      collection = db.P_metadata.T

      index = 0
      p2core_list = {}
      for project_meta in collection.find():
          project_id = project_meta['ProjectID']
          core_developer_list = [core_developer for core_developer in project_meta['Core']]
          p2core_list[project_id] = core_developer_list
      
          if index % 1000000 == 0:
              print("index", index)
      
          index += 1
      
      # save p2core_list 

will give me an error message, 

        Traceback (most recent call last):
          File "get_project2core_member.py", line 57, in <module>
            for project_meta in collection.find():
          File "/usr/lib64/python2.7/site-packages/pymongo/cursor.py", line 814, in next
            if len(self.__data) or self._refresh():
          File "/usr/lib64/python2.7/site-packages/pymongo/cursor.py", line 776, in _refresh
            limit, self.__id))
          File "/usr/lib64/python2.7/site-packages/pymongo/cursor.py", line 733, in __send_message
            response['starting_from'], self.__retrieved))
        AssertionError: Result batch started from 35983, expected 35982

The program is run on your server (da0) and it seems to be a mongo bug (updating the mongo server might solve the problem?)

2.
You mention the project is deforked, is the core author also de-aliased in the table? 

3.
Could you give explanations about how 'core members' is calculated in this table? (or directs me to a paper that explains this)


Thank you!

**Comment by audrism** [comment]
you need to specify the server "da1" if you are not running on da1

It varies depending on the language you use

**Comment by fhbzc** [comment]
I think I already did in my original script, I also tried your ones but it still doesn't work.
I don't think the server is the issue, because if I only collect 10 items, find().limit(10), it works pretty well. The problem seems only happens if I crawl more than 35,983 items.

**Comment by audrism** [comment]
Check general instructions for mongodb/pymongo for running very large queries without timeout. You may need to 
add options to find in order for cursor not to time out.

**Comment by fhbzc** [comment]
I don't think it's a timeout issue, I have run queries in larger mongo collections, never see this before. Also timeout exception is different from this one I saw. 


The problem will only happen exactly at item 35883;
if you try:

   for project_meta in collection.find().limit(35882):

It will work smoothly, but has this error if you run:


   for project_meta in collection.find().limit(35883):


I've been trying to locate the exact problem, two relevant blog posts I found both require fix from the server side:

https://stackoverflow.com/questions/23247924/mongodb-remove-corrupt-bson

https://jira.mongodb.org/browse/PYTHON-840

**Comment by audrism** [comment]
just checking: have you really tried     " no_cursor_timeout=True"?

**Comment by fhbzc** [comment]
Yes, same error message

**Comment by audrism** [comment]
the so post suggest data corruption, not server issue, why you think it is server?

**Comment by fhbzc** [comment]
Oh I mean needs to be fixed from the server side (e.g. people have write access to the data), not a specific problem with the server

**Comment by audrism** [comment]
Looks like the data are fine, the following script went over 6.5M records so far and no problems. I'll let you know if there will be any issues, but I doubt.
```javascript
var cursor = collection.find( );
var row = 0;
while (cursor.hasNext()) {
   val=tojson(cursor.next()));
   row++;
  print(row)
}
```

You may consider checking the version of pymongo you are using if the above script is able to traverse all ~66M rows. I assume that it will finish sometime tomorrow. 

Alternatively, it seems that you need all core teams: in such case database is a poor substitute for the source files
```bash
ls /da?_data/basemaps/gz/*core*
/da5_data/basemaps/gz/P2coreFullT0.s   /da5_data/basemaps/gz/P2coreFullT19.s  /da5_data/basemaps/gz/P2coreFullT29.s
/da5_data/basemaps/gz/P2coreFullT1.s   /da5_data/basemaps/gz/P2coreFullT2.s   /da5_data/basemaps/gz/P2coreFullT3.s
/da5_data/basemaps/gz/P2coreFullT10.s  /da5_data/basemaps/gz/P2coreFullT20.s  /da5_data/basemaps/gz/P2coreFullT30.s
/da5_data/basemaps/gz/P2coreFullT11.s  /da5_data/basemaps/gz/P2coreFullT21.s  /da5_data/basemaps/gz/P2coreFullT31.s
/da5_data/basemaps/gz/P2coreFullT12.s  /da5_data/basemaps/gz/P2coreFullT22.s  /da5_data/basemaps/gz/P2coreFullT4.s
/da5_data/basemaps/gz/P2coreFullT13.s  /da5_data/basemaps/gz/P2coreFullT23.s  /da5_data/basemaps/gz/P2coreFullT5.s
/da5_data/basemaps/gz/P2coreFullT14.s  /da5_data/basemaps/gz/P2coreFullT24.s  /da5_data/basemaps/gz/P2coreFullT6.s
/da5_data/basemaps/gz/P2coreFullT15.s  /da5_data/basemaps/gz/P2coreFullT25.s  /da5_data/basemaps/gz/P2coreFullT7.s
/da5_data/basemaps/gz/P2coreFullT16.s  /da5_data/basemaps/gz/P2coreFullT26.s  /da5_data/basemaps/gz/P2coreFullT8.s
/da5_data/basemaps/gz/P2coreFullT17.s  /da5_data/basemaps/gz/P2coreFullT27.s  /da5_data/basemaps/gz/P2coreFullT9.s
/da5_data/basemaps/gz/P2coreFullT18.s  /da5_data/basemaps/gz/P2coreFullT28.s
```

**Comment by fhbzc** [comment]
Got it, thank you! 

Yeah I think I will parse the source file for this!

**Comment by fhbzc** [comment]
Can I also ask what's the basis for 'core member' to be calculated? Is there a paper explaining the algorithms?

**Comment by audrism** [comment]
closing the issue
