### ISSUE TITLE
Is it save to assume project names doesn't differentiate between upper and lower case?

### ISSUE THREAD

**Issue by fhbzc** [woc-hack/tutorial#20]
In GitHub, project name(or repo_slug) doesn't differentiate between its upper and lower case, for example "woc-hack/tutorial" and "woc-hack/tutoriaL" will be directed to the same page;

Is it save to assume all project name in this dataset doesn't differentiate between upper or lower case as well? 
Specifically, I see some projects have very similar name (e.g. /da5_data/basemaps/gz/P2coreFullT0.s has project '123456qwer_learnGit' and '123456qwer_learngit', they are recorded as two different projects and have different core members'. How should I interpret the result?

**Comment by audrism** [comment]
1. The data is not just from GH, so the case does matter. 
2. The data was collected over decades using different methods. Some attempts at unifying project naming have been made, but there may still be instances where the same project exists twice (or more times) with different case as you noticed.
3. Unifying project naming may be a good small hackathon  project: all you need to do is to turn all to lowercase and list matches

**Comment by fhbzc** [comment]
Got it, that answers the question!
