### ISSUE TITLE
Output in bytes not strings when using oscar.py

### ISSUE THREAD

**Issue by fhbzc** [woc-hack/tutorial#23]
Hello:
    I tried to use oscar and get all commits for a given author following the instructions. I run the following code:

          >>> from oscar import Author
          >>> Author('"Albert Krawczyk" <pro-logic@optusnet.com.au>').commit_shas

It gives me a bunch of bytes instead of the strings as shown in your example. Below is my output:
          
          (b'\x17\xab\xdb\xdc\x90\x19P\x16D*j\x8d\xd8\xe3\x8d\xea\x82R\x92\xae', b'\x9c\xdc\x91\x8b\xfb\xa1\x01\r\xe1]\x0c\x96\x8a\xf8\xee7\xc9\xc3\x00\xff', b'\xd9\xfch\ni\x19\x83\x00\xd3K\xc7\xe3\x1b\xba\xfe6\xe7\x18\\v')

Can you tell how can I fix this problem?

**Comment by audrism** [comment]
This works as designed. All sha1s are internally stored in byte representation for speed/storage. So if you want to look something up, it is wasteful to first convert to hex as it will need to be converted back. 

For printing, the conversion to/from byte to hex representation can be done as in the code
binascii.hexlify(bytes).decode('ascii')

**Comment by fhbzc** [comment]
Got it. Thank you!
