### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by fhbzc** [woc-hack/tutorial#25]
Hello:
    I'm running the following command to get all commits to a project
echo 'project_name' | ~/lookup/getValues -f P2fb | cut -d\; -f2 | ~/lookup/getValues -f b2c > b2c.tmp; 

I'm getting the 
"ssh: connect to host da5 port 22: Connection timed out"
error.

It seems to be some connection error, is there a way to fix this?

Thank you

**Comment by audrism** [comment]
ssh for da5 is on port 443

Try the latest version of lookup (git pull) and let me know if it works

**Comment by fhbzc** [comment]
Hi Audris:
    It seems to be working now! Will let you know if the same problem happen again!
    Thank you very much!
