### ISSUE TITLE
List of potentially inconsistent projects on WoC MongoDB database

### ISSUE THREAD

**Issue by tapjdey** [woc-hack/tutorial#29]
A few projects on the WoC MongoDB database are showing some non-obvious inconsistencies. Request to have a look at them. A few examples are listed below:

| URL                                          | WoC name                  | WoC stars | GH Stars |
|----------------------------------------------|---------------------------|-----------|----------|
| https://github.com/auto-program/vendor       | auto-program_vendor       | 285958    | 0        |
| https://github.com/frioux/dotfiles           | frioux_dotfiles           | 467739    | 53       |
| https://github.com/Reese-D/my_emacs          | Reese-D_my_emacs          | 233391    | 0        |
| https://github.com/bloomberg/chromium.bb     | bloomberg_chromium.bb     | 219233    | 264      |
| https://github.com/Jackeagle/kernel_msm-3.18 | Jackeagle_kernel_msm-3.18 | 201441    | 1        |

**Comment by audrism** [comment]
[auto-program/vendor](https://github.com/auto-program/vendor) actually has tons of stars in ghtorrent dump, but it also has 36K forks (community detected); why it lost these stars is a mystery

https://github.com/Reese-D/my_emacs also appars to be clustered with 38K repos that appear to be unrelated, but some with many stars, e.g. OmniSharp_omnisharp-vscode; ghtorrent has tons of stars associated with it: culd it be a bug in gh_torrent?

**Comment by tapjdey** [comment]
Since these are GHTorrent problems, not sure if they can be fixed
