### ISSUE TITLE
dead links

### ISSUE THREAD

**Issue by MohammadEglil** [woc-hack/tutorial#31]
Under title "[Tutorial: basics of using WoC](https://github.com/woc-hack/tutorial#tutorial-basics-of-using-woc)", the third point "WoC website" seems not to work. 

Under title "[Related background reading](https://github.com/woc-hack/tutorial#related-background-reading)" the first link "Estimate the impact of your code" does not work either.

**Comment by loconous** [comment]
da2.eecs.utk.edu is now back up - you will have to proceed under http, so please hit advanced settings and then proceed to the website.
