### ISSUE TITLE
ssh da4 in tutorial video

### ISSUE THREAD

**Issue by MohammadEglil** [woc-hack/tutorial#32]
In the tutorial video, it is mentioned that one has to use the da4 server in order to execute the shell commands, but on the tutorial page everything is done with the da0 server and it worked fine for me. 

So for example:
In the tutorial video: 
`[username@da0]~% echo 009d7b6da9c4419fe96ffd1fffb2ee61fa61532a | ssh da4 ~/lookup/showCnt.perl 3`

while on the tutorial page:
`[username@da0]~% echo 009d7b6da9c4419fe96ffd1fffb2ee61fa61532a | ~/lookup/showCnt commit 3`

**Comment by audrism** [comment]
Thank you for noticing this. It was indeed a source of confusion and the implementation was changed to be able to run from any server. 
Also, blobs were originally stored on a single server but now they are distributed removing the performance advantage of running on da4.

The next video will not mention this.

**Comment by loconous** [comment]
@MohammadEglil could you please check now and resolve if you encounter no issues?
