### ISSUE TITLE
string encoding in Python API

### ISSUE THREAD

**Issue by MohammadEglil** [woc-hack/tutorial#33]
When I follow [exercise 4a](https://github.com/woc-hack/tutorial#exercise-4a--get-a-list-of-commits-made-by-a-specific-author) and execute the following command:
`>>> Author('"Albert Krawczyk" <pro-logic@optusnet.com.au>').commit_shas`
I get binary strings for the commits while in the tutorial video and on the tutorial page, one gets normal strings. 

So I get: 
`(b'\x17\xab\xdb\xdc\x90\x19P\x16D*j\x8d\xd8\xe3\x8d\xea\x82R\x92\xae', b'\x9c\xdc\x91\x8b\xfb\xa1\x01\r\xe1]\x0c\x96\x8a\xf8\xee7\xc9\xc3\x00\xff', b'\xd9\xfch\ni\x19\x83\x00\xd3K\xc7\xe3\x1b\xba\xfe6\xe7\x18\\v')`

While the tutorial page suggests:
`('17abdbdc90195016442a6a8dd8e38dea825292ae', '9cdc918bfba1010de15d0c968af8ee37c9c300ff', 'd9fc680a69198300d34bc7e31bbafe36e7185c76')`

**Comment by audrism** [comment]
Fixed tutorial
