### ISSUE TITLE
P2tac & c2fbb maps do not exist in lookup API

### ISSUE THREAD

**Issue by MohammadEglil** [woc-hack/tutorial#34]
If I execute the command `echo '<project-name>'  | ~/lookup/getValues P2tac` then I would get `no map P2tac`. Likewise for `c2fbb` map. I tested the command on da0 and da4 servers.

(There are other maps which seem to not work either, like `P2core`,`a2b`, `c2ta` etc.)

**Comment by audrism** [comment]
Not all maps are translated into indexes, for the full list of indexes see:
```
ls /da?_fast/*U.0.tch
/da4_fast/b2AFullU.0.tch   /da5_fast/A2bFullU.0.tch   /da5_fast/P2cFullU.0.tch    /da5_fast/c2bFullU.0.tch    /da5_fast/p2aFullU.0.tch
/da4_fast/b2PFullU.0.tch   /da5_fast/A2cFullU.0.tch   /da5_fast/P2fbFullU.0.tch   /da5_fast/c2ccFullU.0.tch   /da5_fast/p2cFullU.0.tch
/da4_fast/b2aFullU.0.tch   /da5_fast/A2fFullU.0.tch   /da5_fast/a2cFullU.0.tch    /da5_fast/c2datFullU.0.tch  /da5_fast/w2MbFullU.0.tch
/da4_fast/b2fAFullU.0.tch  /da5_fast/A2fbFullU.0.tch  /da5_fast/b2MwFullU.0.tch   /da5_fast/c2pFullU.0.tch    /da5_fast/w2mbFullU.0.tch
/da4_fast/b2fFullU.0.tch   /da5_fast/P2AFullU.0.tch   /da5_fast/b2obFullU.0.tch   /da5_fast/c2pcFullU.0.tch
/da4_fast/b2faFullU.0.tch  /da5_fast/P2aFullU.0.tch   /da5_fast/b2tacFullU.0.tch  /da5_fast/c2rhpFullU.0.tch
/da5_fast/A2PFullU.0.tch   /da5_fast/P2bFullU.0.tch   /da5_fast/c2PFullU.0.tch    /da5_fast/ob2bFullU.0.tch

```

As described in the tutorial, maps are in /da?_data/basemaps/gz. You can see full list via
```
ls /da?_data/basemaps/gz/*U0.s
```

If you have a clear use case for random access to a map that is not currently indexed, please let me know.
Otherwise you can just zcat ...|grep  for what you need.

**Comment by MohammadEglil** [comment]
Thank you for your reply! I misunderstood certain things...my bad.
