### ISSUE TITLE
command in Activity S4 does not work for da5 server

### ISSUE THREAD

**Issue by MohammadEglil** [woc-hack/tutorial#35]
When execute the command `echo 009d7b6da9c4419fe96ffd1fffb2ee61fa61532a | ssh da5 ~/lookup/cmputeDiff3T.perl` from da0 server like [described](https://github.com/woc-hack/tutorial#activity-s4-plumbing-of-woc), then I would get `cant open /fast/All.sha1o/sha1.tree_0.tch`.
However,  it does work from da4 server.

**Comment by audrism** [comment]
Fixed. You may want to pull on lookup to get cmputeDiff

**Comment by loconous** [comment]
@MohammadEglil could you please check now and resolve if you encounter no issues? Thanks
