### ISSUE TITLE
How to find repositories containing a specific file?

### ISSUE THREAD

**Issue by gaokai320** [woc-hack/tutorial#39]
Hi, Audris. I want to find all repositories containing a Dockerfile. And you know, a Dockerfile may appear in the root folder or subfolders. A possible solution I catch up is to iterate all files via f2P or f2p zipped files or iterate all projects containing python files like P2f or p2f. 
I checked maps in /da?_data/basemaps/gz and /da?_fast, but didn't find related maps except the T version P2f maps in /da5_fast. So I am wondering if there are efficient ways to achieve this via U version maps? Thank you!

**Comment by audrism** [comment]
are you looking for something like:
```
for i in {0..127}; do 
zcat c2fFullU$i.s|grep Dockerfile|join -t\; <(zcat c2pFullU$i.s) - | cut -d\; -f2-
done
```

**Comment by gaokai320** [comment]
Yes! That's exactly what I want. Thank you! 
Btw, has woc considered to provide information on the tool-related files or folders about each repository? By tool-related files, they are, for example, github action folder(.github/workflow), dockerfiles, requirements.txt, setup.py, packages.json, pom.xml, etc. These files or folders are indicators of the tool adoption of a repository and can be used to analyze the dependency relationships, tool usage, etc. If provided, it would be convenient to conduct related analysis.

**Comment by gaokai320** [comment]
Besides, I notice c2fbb maps in /da5_data/basemaps/gz miss partition 8 and 9. But I didn't find how to generate these two partition from [lookup](https://bitbucket.org/swsc/lookup). It seems that these maps are generated based on [c2fbbFullT and TU](https://bitbucket.org/swsc/lookup/src/4a9ceed1e7429be83284bf946aa54f3854a55b0f/b2ob.pbs?at=master#lines-47). But I can not find related scripts

**Comment by audrism** [comment]
It would be good to have tools realtionship either at the project or even at the commit level. 

Various type of build and test tools such as docker, cmake, ant, junit, rake, etc

Thanks for noticing missing files: should be there now.
