### ISSUE TITLE
Problem with connecting to the mongodb

### ISSUE THREAD

**Issue by TitovS** [woc-hack/tutorial#42]
First of all thank you for the great resource for the SE research community!

I have problems connecting to the mognodb instance on da1. I've tried to replicate the steps in tutorial and still geting connection refusal.

```
titovs@da0:~>mongosh --host=da1
Current Mongosh Log ID:	63b6e82856394759da624f53
Connecting to:		mongodb://da1:27017/?directConnection=true&appName=mongosh+1.6.1
MongoNetworkError: connect ECONNREFUSED
```

Also tried to connect with mongo and thought python -- still getting connection refused. 
I was able to access mongodb last time on the first of November.

**Comment by audrism** [comment]
Please replace da1 to da5
(this is due to da2 going down and being fixed)

https://discord.com/channels/954408789203886151/1005362597761130577

**Comment by TitovS** [comment]
Thanks! It helped! Also joined discord!
