### ISSUE TITLE
Some inconsistencies among MongoDB, P2a map, and p2a map

### ISSUE THREAD

**Issue by tapjdey** [woc-hack/tutorial#44]
I was looking at the project https://github.com/elastic/elasticsearch and found some inconsistencies - 
If I run the `P2a` map, it gives me some strange (and wrong result).
```
$ echo elastic_elasticsearch | ~/lookup/getValues P2a
elastic_elasticsearch;elastic_elasticsearch
```
However, the `p2a` map correctly shows the list of authors.

I also found that this project does not exist in MongoDB, which is a bit strange given is has been active for quite some time now.
However, I could find a whole bunch derivative projects (see below) in MongoDB but the main repo is missing:

> elastic_elasticsearch-js
> elastic_elasticsearch-perl
> elastic_elasticsearch-py
> elastic_elasticsearch-rails
> elastic_elasticsearch-net
> elastic_elasticsearch-definitive-guide
> elastic_elasticsearch-ruby
> elastic_elasticsearch-dsl-py
> elastic_elasticsearch-hadoop

**Comment by audrism** [comment]
To get P use:
echo elastic_elasticsearch | ~/lookup/getValues p2P
elastic_elasticsearch;bitbucket.org_mirror_elasticsearch

so |echo elastic_elasticsearch | ~/lookup/getValues P2a|
should be empty

But script had a bug: it returned a compressed key if value is nul for s cs types

Fixed and pushed

Audris

**Comment by tapjdey** [comment]
Thank you!
