### ISSUE TITLE
How to use c2fbb  table

### ISSUE THREAD

**Issue by fhbzc** [woc-hack/tutorial#46]
Hello:

I have a list of commits I'm interested in, and I want to get the blobs changed by them. After reviewing the document, I think c2fbb is the table to use.

Initially, I'm trying to use **~/lookup/getValues c2fbb**    to get the information from, but it says **no map**. 

Then I try to use join command and get the raw data from /da5_data/basemaps/gz/c2fbbFullU*.s, by running the following command:

     join -t\; -1 2 -2 1 <(cat ./sorted_valid_commit_list_Python.data) <(zcat /da5_data/basemaps/gz/c2fbbFullU*.s | ~/lookup/lsort 30G -t\; -k1,1) > commit_blob_change_Python.data

sorted_valid_commit_list_Python.data is the list of commit shas I use, which is stored as txt.

But it seems to take forever. any suggestions on how to get the information I want?

Thank you!

**Comment by audrism** [comment]
c2fbb relation is in a set of 128 sorted flat files (c2fbbFullUXXX.s)

Hence the procedure is like that where a very large number of lookups is needed:
```
cat list | perl ~/lookup/splitSec.perl list. 128
for i in {0..127}; do
zcat list.$i.gz|lsort 2G -u | gzip > list.$i.s
done  
for i in {0..127}; do
zcat list.$i.s| join -t\; <(zcat properPath/c2fbbFullU$i.s) - 
done | gzip > list.c2fbb
```

**Comment by audrism** [comment]
If you were to prioritize, which one should be the first?
c2fbb, bb2cf, obb2cf?

**Comment by audrism** [comment]
That you can get piping commit shas into compDiff3.perl on da5.
It's not very fast as the diff needs to be calculated, but for few hundred
to few thousand should work.

**Comment by audrism** [comment]
c2fbb version V is on da3, output will have c followed by all tuples fbb concatenated together

**Comment by audrism** [comment]
bb2cf version V will be on da3 (in a couple of days), output will have new blob followed by all tuples bcf concatenated together

**Comment by loconous** [comment]
@k----n, could you please verify if this issue is still relevant? Thanks

**Comment by loconous** [comment]
Closing this issue as per @k----n's comment. @fhbzc please feel free to re-open if you feel like this issue is not resolved, but @audrism previously provided best approach. Additionally, please make sure to check version V.
