### ISSUE TITLE
What is the recommend way to get all projects that contains a file sha?

### ISSUE THREAD

**Issue by gaokai320** [woc-hack/tutorial#47]
I want to find all projects containing a file given the file's sha1 values. For example, take the file 02840498cb662567eca257d60f4b496a034df4af file (which is the `setup.py` file in Chia-Network_chia-blockchain project) as an example, I first obtain all commits that introduce this file:
```shell
echo 02840498cb662567eca257d60f4b496a034df4af | ~/lookup/getValues b2tac
02840498cb662567eca257d60f4b496a034df4af;1632863451;William Blanke <wjb98672@gmail.com>;f25c2290d6235033a8dd1842cf2dee9770dfd5bd;1633757357;Water-Networks <water2066@hotmail.com>;d5662784e44a09a4be1c3a93ebc036db93675928
```
Then I select the first (also the earliest?) commit in the output to obtain all projects containing this commit:
```shell
echo f25c2290d6235033a8dd1842cf2dee9770dfd5bd | ~/lookup/getValues c2p
f25c2290d6235033a8dd1842cf2dee9770dfd5bd;Flax-Network_flax-blockchain;cmmarslender_chia-release-test;felixbrucker_chia-blockchain
```
**But Chia-Network_chia-blockchain dos not appear in the output.**

If I use the c2P map, then, it appears:
```shell
echo f25c2290d6235033a8dd1842cf2dee9770dfd5bd | ~/lookup/getValues c2P
f25c2290d6235033a8dd1842cf2dee9770dfd5bd;Chia-Network_chia-blockchain
```
Or if I use the b2P map, it also appears with another project:
```shell
echo 02840498cb662567eca257d60f4b496a034df4af | ~/lookup/getValues b2P
02840498cb662567eca257d60f4b496a034df4af;Chia-Network_chia-blockchain;Water-Networks_water-blockchain
```

So, I am wondering **what is the recommended and the most accurate way to get all projects that contain a file sha?**

I notice the note in the README.md that:
> Note: c2P returns the most central repository for this commit, and does not include repos that forked off of this commit. P2c returns ALL commits associated with this repo, including commits made to forks of this particular repo.

How is the **most central repository for this commit** defined?

**Comment by audrism** [comment]
1. to get all projects you need to get all commits that create the sha1: b2obcfFullV*s then do commit to project map
2. most central repo is done via deforking see tutorial note
(via Leuwen community
detection on commit / repo bi-graph: https://arxiv.org/abs/2002.02707)

**Comment by gaokai320** [comment]
1. When do commit to project map, which one is better? **c2p** or **c2P**? It seems that the two maps generate different results. (See examples above)? Also, I can not find b2obcfFullV*s but obb2cfFullV*s in /da7_data/basemaps/gz. And is there generated tch databases, which is much faster than gzipped files for random access?
2. I go through the referred paper, and do not find a description on the most central repo except this sentence in Page 3: "Names of the clusters are chosen by selecting a repository from the cluster that has the shortest name that and is first in the alphanumeric order"

**Comment by audrism** [comment]
1. It depends if you are looking for deforked projects or original repos
2. Correct, ther has been an upgrade in the algorithm as the shortest name is not necessarily the most representative repo. It uses Katz centrality.

**Comment by gaokai320** [comment]
Thank You!
