### ISSUE TITLE
error reading some blob contents

### ISSUE THREAD

**Issue by mahmoudjahanshahi** [woc-hack/tutorial#51]
While trying to read blob contents, I got this error for some blobs:

The code:
`zcat data/bLICENSEFullU.s | 
~/lookup/showCnt blob 1 2>data/bL2cnt.noBlob | 
gzip >data/bL2cnt.gz; 
`

The error:
`Error: compressed data corrupted (size mismatch) at /home/mjahansh/lookup/woc.pm line 209.
, msg=2;1682924185652;022caa4a4c5e9dedc03522558fbbff6bab45e35a, code=
Error: compressed data corrupted (size mismatch) at /home/mjahansh/lookup/woc.pm line 215.
, 2;1682924185652;022caa4a4c5e9dedc03522558fbbff6bab45e35a, 
Error: compressed data corrupted (size mismatch) at /home/mjahansh/lookup/woc.pm line 209.
, msg=2;1682924160035;0279e05e6f5e1f11bfc38e4783b8e21cf6a30382, code=
Error: compressed data corrupted (size mismatch) at /home/mjahansh/lookup/woc.pm line 215.
, 2;1682924160035;0279e05e6f5e1f11bfc38e4783b8e21cf6a30382, 
Error: compressed data corrupted (size mismatch) at /home/mjahansh/lookup/woc.pm line 209.
, msg=2;1681506925558;02c990fea301476832d3d2d7ef509c8a1f132022, code=`

**Comment by audrism** [comment]
```
echo 022caa4a4c5e9dedc03522558fbbff6bab45e35a|~/lookup/showCnt blob
```
works for me: where is data/bLICENSEFullU.s?

**Comment by mahmoudjahanshahi** [comment]
data is at ~mjahansh/repos/lcs/data/

Apparently this error only happens when I do it from da4. I tried da0-5 and only da4 gives this error.

**Comment by audrism** [comment]
got it, it was an optimization to use local offset files. Removed it but you need to pull to get fixes

**Comment by mahmoudjahanshahi** [comment]
Great, works now, thanks!
