### ISSUE TITLE
no map P2c error

### ISSUE THREAD

**Issue by fhbzc** [woc-hack/tutorial#52]
Hello:

   I'm using 

     ~/lookup/getValues -f P2c < list_of_woc_project.data > list_of_commits.data

   command to get all commits for the list of projects I have, but I get the error

    no map P2c

Is there a bug with the P2c table? (I have been using this command for quite long time, no problems until now)

Thanks.

**Comment by audrism** [comment]
have you pulled the latest version of lookup?

**Comment by fhbzc** [comment]
Hi Audris:

   I just delete my lookup and use 

     git clone https://bitbucket.org/swsc/lookup
   
   to get the lookup again (I'm assuming it should be the latest version)

   But I still have the same error.

**Comment by audrism** [comment]
Whats your username: I can not reproduce the error

**Comment by fhbzc** [comment]
My user name is bobo

**Comment by fhbzc** [comment]
I see, I'm not using the new version I just downloaded, maybe that's what causes the problem.

Thank you very much for your response!
