### ISSUE TITLE
c2Ptabfl{Pkg,Def}FullV{0..127}.s - (a2A) 

### ISSUE THREAD

**Issue by mahmoudjahanshahi** [woc-hack/tutorial#55]
Seems like the authors have not been aliased in version V of these tables. We had c2PtAbfl{Pkg,Def}FullU{0..127}.s in version U and now c2Ptabfl{Pkg,Def}FullV{0..127}.s in version V.

**Comment by audrism** [comment]
Copied files from isaac ng
