### ISSUE TITLE
ver V API

### ISSUE THREAD

**Issue by mahmoudjahanshahi** [woc-hack/tutorial#57]
Seems like some API's are still running on ver U. Specifically, I faced this when using getValues b2f. Look at the following example:

    echo ffa3483d7cc948a863527510fc1a4964757bde6b | ~/lookup/getValues -f b2f 
    No ffa3483d7cc948a863527510fc1a4964757bde6b in /fast/b2fFullU

Nevertheless, they are in version V tables:

    zcat /da?_data/basemaps/gz/b2fFullV127.s | grep "^ffa3483d7cc948a863527510fc1a4964757bde6b"  
    ffa3483d7cc948a863527510fc1a4964757bde6b;LICENSE.md/project.html  
    ffa3483d7cc948a863527510fc1a4964757bde6b;project.html

Interestingly enough, they can even be found in ver U tables:

    zcat /da?_data/basemaps/gz/b2fFullU127.s | grep "^ffa3483d7cc948a863527510fc1a4964757bde6b"
    ffa3483d7cc948a863527510fc1a4964757bde6b;LICENSE.md/project.html
    ffa3483d7cc948a863527510fc1a4964757bde6b;project.html

So it seems like a problem with fast tables.

**Comment by audrism** [comment]
Added version V
```
> echo ffa3483d7cc948a863527510fc1a4964757bde6b | ~/lookup/getValues -f b2f ffa3483d7cc948a863527510fc1a4964757bde6b;LICENSE.md/project.html
ffa3483d7cc948a863527510fc1a4964757bde6b;project.html
```
