### ISSUE TITLE
showCnt commit

### ISSUE THREAD

**Issue by mahmoudjahanshahi** [woc-hack/tutorial#59]
The showCnt API for commit is not working. The example from tutorial:

    [mjahansh@da0]~% echo 009d7b6da9c4419fe96ffd1fffb2ee61fa61532a | ~/lookup/showCnt commit
    cant open /fast/All.sha1c/commit_0.tch

**Comment by audrism** [comment]
Please git update you lookup

**Comment by mahmoudjahanshahi** [comment]
It is already up to date:

    [mjahansh@da4]~/lookup% git pull && echo 009d7b6da9c4419fe96ffd1fffb2ee61fa61532a | ~/lookup/showCnt commit
    Already up-to-date.
    cant open /fast/All.sha1c/commit_0.tch

**Comment by audrism** [comment]
oops, please try now

**Comment by mahmoudjahanshahi** [comment]
thanks!
